# Generated by Django 5.2.10 on 2026-02-10 05:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('user_registered', 'User Registered'), ('user_login', 'User Login'), ('role_changed', 'Role Changed'), ('user_deleted', 'User Deleted'), ('video_created', 'Video Created'), ('video_updated', 'Video Updated'), ('video_deleted', 'Video Deleted'), ('profile_updated', 'Profile Updated')], max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
